import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react'
import { NextAuthProvider } from '@/components/NextAuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootProps {
  children: React.ReactNode,
  session: any
}

export default function RootLayout({
  children,
  session
}: RootProps) {
  return (
    <html lang="en">
      <NextAuthProvider session={session}>
        <body className={inter.className}>{children}</body>
      </NextAuthProvider>
    </html>
  )
}
