import './globals.css'
import type { Metadata } from 'next'
import React from 'react'
import { NextAuthProvider } from '@/components/NextAuthProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootProps {
  children: React.ReactNode,
  session: any
}

export default function RootLayout({
  children,
  session
}: RootProps) {
  return (
    <html lang="en">
      <NextAuthProvider session={session}>
        <body className="h-screen bg-gradient-to-r from-zinc-900 from-30% to-purple-950 to-95% flex justify-center">
          <div className='flex flex-1'>
            {children}
          </div>
        </body>
      </NextAuthProvider>
    </html>
  )
}
