import { AdminHeader } from '@/components/AdminHeader'
import type { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface AdminProps {
  children: React.ReactNode,
}

export default function AdminLayout({ children }: AdminProps) {
  return (
    <div className='flex flex-1 flex-col'>
      <AdminHeader />
      {children}
    </div>
  )
}
